/**
 * name : common.js
 * author : Aman Karki
 * Date : 13-July-2020
 * Description : All common messages.
 */

const ORG_EXTENSION_VISIBILITY = {
	ALL: 'ALL',
	CURRENT: 'CURRENT',
	ASSOCIATED: 'ASSOCIATED',
}

module.exports = {
	ORG_EXTENSION_VISIBILITY,
	ACTIVE_STATUS: 'active',
	PUBLISHED: 'published',
	ASSESSMENT: 'assessment',
	CONTENT: 'content',
	IMPROVEMENT_PROJECT: 'improvementProject',
	MULTIPLE: 'multiple',
	OTHERS: 'Others',
	SIMPLE_TASK_TYPE: 'simple',
	NOT_STARTED: 'not started',
	RECENTLY_ADDED_PROJECT: 'currentlyAdded',
	IMPORTANT_PROJECT: 'importantProject',
	COMPLETED_STATUS: 'completed',
	INPROGRESS_STATUS: 'inProgress',
	NOT_STARTED_STATUS: 'notStarted',
	STARTED: 'started',
	SUBMITTED_STATUS: 'submitted',
	OBSERVATION: 'observation',
	PUBLISHED_STATUS: 'published',
	LEAD_ASSESSOR: 'LEAD_ASSESSOR',
	PROJECT_DESCRIPTION:
		'Manage and track your school improvement easily, by creating tasks and planning project timelines.',
	RESOURCE_TYPE: 'Improvement Project Solution',
	ENGLISH_LANGUAGE: 'English',
	KEYWORDS: 'Improvement Project',
	ASSIGN_TO_ME: 'assignedToMe',
	CREATED_BY_ME: 'createdByMe',
	DEFAULT_PAGE_NO: 1,
	DEFAULT_PAGE_SIZE: 100,
	OBSERVATION_REFERENCE_KEY: 'observation',
	ALLOW_MULTIPLE_ASSESSMENTS: 'allowMultipleAssessemts',
	IS_RUBRIC_DRIVEN: 'isRubricDriven',
	CRITERIA_LEVEL_REPORT: 'criteriaLevelReport',
	LINK: 'link',
	DEFAULT_SUBMISSION_REQUIRED: 1,
	TASK_SEQUENCE: 'taskSequence',
	CHILDREN: 'children',
	ATTACHMENT_TYPE_LINK: 'link',
	PROJECT_ATTACHMENT: 'project',
	TASK_ATTACHMENT: 'task',
	DEFAULT_TASK_COMPLETED: 0,
	IMAGE_DATA_TYPE: 'image/jpeg',
	DISTRICT: 'district',
	SERVER_TIME_OUT: 5000,
	OK: 'OK',
	PROJECT: 'project',
	PROJECT_CERTIFICATE_GENERATED_SUCCESSFULLY: 'Certificate generated successfully',
	DISCOVERED_BY_ME: 'discoveredByMe',
	COURSE: 'course',
	SURVEY: 'survey',
	INACTIVE: 'inactive',
	ALL_ROLES: 'all',
	OFF: 'OFF',
	DEFAULT_SURVEY_REMOVED_DAY: 15,
	END_DATE: 'endDate',
	START_DATE: 'startDate',
	SCHOOL: 'school',
	INSTITUTIONAL: 'institutional',
	PREFIX_FOR_SOLUTION_LINK: 'view',
	CREATE_OBSERVATION: '/create-observation/',
	CREATE_PROJECT: '/project/',
	CREATE_COURSE: '/create-course/',
	CREATE_SURVEY: '/create-survey/',
	SUBMISSION_STATUS_COMPLETED: 'completed',
	EXPIRED: 'expired',
	STARTED: 'started',
	AWS_SERVICE: 'AWS',
	WRITE_PERMISSION: 'w',
	READ_PERMISSION: 'r',
	PUBLIC: 'public',
	PRIVATE: 'private',
	AWS: 'aws',
	AZURE: 'azure',
	GCP: 'gcloud',
	OCI: 'oci',
	SUCCESS: 'SUCCESS',
	STATUS_FAILURE: 'FAILURE',
	PDF_REPORT_GENERATED_: 'PDF_REPORT_GENERATED_SUCCESSFULLY',
	COULD_NOT_GENERATE_PDF: 'COULD_NOT_GENERATE_PDF_REPORT',
	SOLUTION_MODEL_NAME: 'solutions',
	TARGETED_SOLUTION_TEXT:
		'View and participate in educational programs active in your location and designed for the role you selected',
	PROJECT_VISIBILITY_ALL: 'ALL',
	PROJECT_VISIBILITY_SELF: 'SELF',
	PROJECT_VISIBILITY_SPECIFIC: 'SPECIFIC',
	PROJECT_VISIBILITY_SCOPE: 'SCOPE',
	DEFAULT_ACL: {
		visibility: 'SELF',
		users: [],
		scope: {},
	},
	DEFAULT_ATTRIBUTES: [
		{
			name: 'Duration',
			code: 'duration',
			hasEntityTrue: true,
			entities: [
				{
					value: '1 week',
					label: '1 week',
				},
				{
					value: '2 week',
					label: '2 week',
				},
				{
					value: '3 week',
					label: '3 week',
				},
				{
					value: '4 week',
					label: '4 week',
				},
				{
					value: '5 week',
					label: '5 week',
				},
				{
					value: '6 week',
					label: '6 week',
				},
				{
					value: 'More than 6 weeks',
					label: 'More than 6 weeks',
				},
			],
		},
		{
			name: 'Role',
			code: 'role',
			hasEntityTrue: true,
			entities: [],
		},
	],
	AUTH_METHOD: {
		NATIVE: 'native',
		KEYCLOAK_PUBLIC_KEY: 'keycloak_public_key',
	},
	APP_ELEVATE_PROJECT: 'elevate-project',
	SYSTEM: 'SYSTEM',
	ADMIN_ROLE: 'admin',
	ORG_ADMIN: 'org_admin',
	TENANT_ADMIN: 'tenant_admin',
	DELETE_EVENT_ENTITY: 'user',
	DELETE_EVENT_TYPE: 'delete',
	CREATE_EVENT_TYPE: 'create',
	UPDATE_EVENT_TYPE: 'update',
	OBJECT: 'object',
	STRING: 'string',
	ALL: 'all',
	NONE: 'none',
	ALL_SCOPE_VALUE: 'ALL',
	ADD_OPERATION: 'ADD',
	APPEND_OPERATION: 'APPEND',
	REMOVE_OPERATION: 'REMOVE',
	OVERRIDE_OPERATION: 'OVERRIDE',
	PROMISE_FULFILLED: 'fulfilled',
	DEFAULT_PROGRAM_USER_MAPPING_TOPIC: 'elevate_program_operation',
	PROGRAM: 'program',
	FALSE: 'false',
	BOOLEAN_FALSE: false,
	BOOLEAN_TRUE: true,
	TRUE: 'true',
	OPTIONAL_SCOPE_FIELD: 'optional_factors',
	MANDATORY_SCOPE_FIELD: 'factors',
	SOLUTION: 'solution',
	DEFAULT_ORG_EXTENSION_POLICIES: {
		projectResourceVisibilityPolicy: ORG_EXTENSION_VISIBILITY.CURRENT,
		externalProjectResourceVisibilityPolicy: ORG_EXTENSION_VISIBILITY.CURRENT,
	},
	API_REQUEST_METHODS: {
		GET: 'GET',
		POST: 'POST',
		PATCH: 'PATCH',
		PUT: 'PUT',
		DELETE: 'DELETE',
	},
	SESSION_VERIFICATION_METHOD: {
		USER_SERVICE: 'user_service_authenticated',
	},
}
